import type { ServiceKey } from './services';

export type PromptLanguage = 'ku' | 'ar' | 'en';

export interface PromptChip {
  label: string;
  prompt: string;
}

interface LocalizedText {
  ku: string;
  ar: string;
  en: string;
}

interface LocalizedPrompt {
  label: LocalizedText;
  prompt: LocalizedText;
}

const entry = (
  labelKu: string,
  labelAr: string,
  labelEn: string,
  promptKu: string,
  promptAr: string,
  promptEn: string,
): LocalizedPrompt => ({
  label: { ku: labelKu, ar: labelAr, en: labelEn },
  prompt: { ku: promptKu, ar: promptAr, en: promptEn },
});

const SERVICE_PROMPTS: Record<ServiceKey, LocalizedPrompt[]> = {
  assistant: [
    entry(
      'پلانی دەستپێکردنی بازرگانی',
      'خطة بدء النشاط التجاري',
      'Start a trading business',
      'پلانی هەنگاو بە هەنگاو بۆ دەستپێکردنی بازرگانی و هاوردەکردن لە عێراق بۆم ئامادە بکە و مۆڵەت، تۆمارکردن، باج و لۆجستیک جیا بکەرەوە.',
      'أعد لي خطة خطوة بخطوة لبدء نشاط تجاري واستيرادي في العراق، مع فصل التسجيل والتراخيص والضرائب والخدمات اللوجستية.',
      'Prepare a step-by-step plan for starting a trading and importing business in Iraq, separating registration, licensing, tax, and logistics requirements.',
    ),
    entry(
      'پشکنینی پلانی هاوردە',
      'مراجعة خطة الاستيراد',
      'Review an import plan',
      'پلانی هاوردەکردنی من هەڵبسەنگێنە و کەلێنەکانی بەڵگەنامە، گومرگ، گواستنەوە، پارەدان و بەڕێوەبردنی مەترسی دیاری بکە.',
      'راجع خطة الاستيراد الخاصة بي وحدد الفجوات في المستندات والجمارك والنقل والدفع وإدارة المخاطر.',
      'Review my import plan and identify gaps in documentation, customs, transport, payment, and risk management.',
    ),
    entry(
      'لیستی بەڵگەنامە پێویستەکان',
      'قائمة المستندات المطلوبة',
      'Required document checklist',
      'بەپێی جۆری کاڵا، وڵاتی سەرچاوە و دەروازەی چوونەژوورەوە، checklist ـێکی پیشەیی بۆ بەڵگەنامەکانی هاوردە و تەرخیسکردن دروست بکە.',
      'أنشئ قائمة مهنية بمستندات الاستيراد والتخليص حسب نوع البضاعة وبلد المنشأ ومنفذ الدخول.',
      'Create a professional import and clearance document checklist based on cargo type, origin country, and Iraqi entry point.',
    ),
    entry(
      'بەراوردی ڕێگاکانی هاوردە',
      'مقارنة مسارات الاستيراد',
      'Compare import routes',
      'ڕێگاکانی بەندر و مەرزی وشکانی بۆ بارەکەم لە ڕووی کات، تێچوو، بەڵگەنامە و مەترسی بەراورد بکە و بنەمای پێشنیارەکەت ڕوون بکەرەوە.',
      'قارن مسارات الموانئ والمنافذ البرية لشحنتي من حيث الوقت والتكلفة والمستندات والمخاطر، واشرح أساس توصيتك.',
      'Compare port and land-border routes for my shipment by time, cost, documentation, and risk, and explain the basis of your recommendation.',
    ),
    entry(
      'هەڵسەنگاندنی مەترسی بازرگانی',
      'تقييم المخاطر التجارية',
      'Assess trade risks',
      'مەترسییە یاسایی، دارایی، دابینکەر، گومرگی و لۆجستیکییەکانی مامەڵەیەکی نێودەوڵەتی هەڵبسەنگێنە و پلانی کەمکردنەوەیان بنووسە.',
      'قيّم المخاطر القانونية والمالية ومخاطر المورد والجمارك والخدمات اللوجستية لصفقة دولية، واقترح خطة للتخفيف منها.',
      'Assess the legal, financial, supplier, customs, and logistics risks of an international trade transaction and propose mitigations.',
    ),
  ],
  market: [
    entry(
      'کورتەی بازاڕ بۆ کاڵایەک',
      'ملخص سوق لمنتج',
      'Product market brief',
      'کورتە ڕاپۆرتێکی بازاڕ بۆ کاڵاکەم لە عێراق ئامادە بکە؛ داواکاری، کڕیار، ڕکابەر، نرخی گشتی و سنووردارییەکان جیا بکەرەوە و ئەو زانیارییانە دیاری بکە کە پێویستیان بە پشتڕاستکردنەوەی نوێ هەیە.',
      'أعد موجزاً لسوق منتجي في العراق يشمل الطلب والعملاء والمنافسين ونطاق الأسعار والقيود، وحدد المعلومات التي تحتاج إلى تحقق حديث.',
      'Prepare an Iraqi market brief for my product covering demand, customers, competitors, indicative pricing, and constraints, and flag data requiring current verification.',
    ),
    entry(
      'هەڵسەنگاندنی دەرفەتی بازاڕ',
      'تقييم فرصة السوق',
      'Evaluate a market opportunity',
      'دەرفەتی هێنانەبازاڕی ئەم کاڵایە هەڵبسەنگێنە و TAM، segment ـی کڕیار، کەناڵی فرۆشتن، خاڵی جیاوازی و مەترسییە سەرەکییەکان بە شێوەی فرضی ڕوون بکەرەوە.',
      'قيّم فرصة إدخال هذا المنتج إلى السوق، موضحاً حجم الفرصة التقديري وشرائح العملاء وقنوات البيع والميزة التنافسية والمخاطر الرئيسية.',
      'Evaluate this product opportunity, outlining an indicative market size, customer segments, sales channels, differentiation, and key risks.',
    ),
    entry(
      'چاودێری نیشانەکانی بازاڕ',
      'مراقبة مؤشرات السوق',
      'Monitor market signals',
      'dashboard ـێکی هەفتانە پێشنیار بکە بۆ چاودێریکردنی داواکاری، نرخ، هاوردە، دراو، تێچووی گواستنەوە و گۆڕانکارییە ڕێساییەکان.',
      'اقترح لوحة متابعة أسبوعية للطلب والأسعار والاستيراد والعملات وتكاليف النقل والتغييرات التنظيمية.',
      'Propose a weekly dashboard for monitoring demand, pricing, imports, currency, freight costs, and regulatory changes.',
    ),
    entry(
      'بەراوردی ڕکابەرەکان',
      'تحليل المنافسين',
      'Competitor comparison',
      'چوارچێوەیەکی بەراوردی ڕکابەرەکان دروست بکە کە نرخ، کوالێتی، دابەشکردن، خزمەتگوزاری، متمانە و خاڵی لاواز لەخۆبگرێت.',
      'أنشئ إطار مقارنة للمنافسين يشمل السعر والجودة والتوزيع والخدمة والثقة ونقاط الضعف.',
      'Build a competitor-comparison framework covering price, quality, distribution, service, trust, and weaknesses.',
    ),
    entry(
      'پلانی چوونە ناو بازاڕ',
      'خطة دخول السوق',
      'Market-entry plan',
      'پلانی ٩٠ ڕۆژە بۆ چوونە ناو بازاڕی عێراق بنووسە کە تاقیکردنەوەی داواکاری، نرخدانان، هاوبەش، فرۆشتن و KPI ـەکان لەخۆبگرێت.',
      'اكتب خطة دخول للسوق العراقي لمدة 90 يوماً تشمل اختبار الطلب والتسعير والشركاء والمبيعات ومؤشرات الأداء.',
      'Write a 90-day Iraqi market-entry plan covering demand validation, pricing, partners, sales, and KPIs.',
    ),
  ],
  borders: [
    entry(
      'پشکنینی ڕێکاری دەروازە',
      'متطلبات المنفذ الحدودي',
      'Border procedure checklist',
      'بەپێی جۆری بار و دەروازەی هەڵبژێردراو، ڕێکار و بەڵگەنامە پێشبینیکراوەکان بۆ گەیشتن، پشکنین و تەرخیسکردن لیست بکە و خاڵەکان بۆ پشتڕاستکردنەوە دیاری بکە.',
      'اسرد الإجراءات والمستندات المتوقعة للوصول والفحص والتخليص حسب نوع الشحنة والمنفذ المختار، وحدد ما يجب التحقق منه رسمياً.',
      'List expected arrival, inspection, and clearance procedures for the cargo and selected crossing, flagging items that require official verification.',
    ),
    entry(
      'بەراوردی دوو دەروازە',
      'مقارنة منفذين',
      'Compare two crossings',
      'دوو دەروازەی دیاریکراو بۆ بارەکەم لە ڕووی ماوە، تێچوو، قەرەباڵغی، ژێرخان و مەترسیی تەرخیسکردن بەراورد بکە.',
      'قارن بين منفذين محددين لشحنتي من حيث الزمن والتكلفة والازدحام والبنية التحتية ومخاطر التخليص.',
      'Compare two specified crossings for my shipment by transit time, cost, congestion, infrastructure, and clearance risk.',
    ),
    entry(
      'پلانی دواکەوتنی مەرز',
      'خطة تأخر عند المنفذ',
      'Border-delay response plan',
      'پلانی کارکردن بۆ دواکەوتنی بار لە مەرز بنووسە؛ پەیوەندییەکان، بەڵگەنامەی پێویست، escalation و هەڵبژاردەی ڕێگای جێگرەوە تێدا بێت.',
      'اكتب خطة استجابة لتأخر الشحنة عند المنفذ تشمل الاتصالات والمستندات والتصعيد وخيارات المسار البديل.',
      'Create a response plan for a border delay, including contacts, documents, escalation, and alternate-route options.',
    ),
    entry(
      'ئامادەکاری پێش گەیشتن',
      'الاستعداد قبل الوصول',
      'Pre-arrival preparation',
      'checklist ـێکی ٧٢ کاتژمێر پێش گەیشتنی بار بۆ کەمکردنەوەی وەستان و خەرجی زیادە ئامادە بکە.',
      'أنشئ قائمة تحقق قبل الوصول بـ72 ساعة لتقليل التوقف والتكاليف الإضافية عند المنفذ.',
      'Create a 72-hour pre-arrival checklist to reduce border dwell time and additional charges.',
    ),
    entry(
      'هەڵسەنگاندنی دۆخی دەروازە',
      'تقييم حالة المنفذ',
      'Assess crossing status',
      'بڵێ بۆ هەڵسەنگاندنی دۆخی ئێستای دەروازە کام سەرچاوە و نیشانەکان بپشکنم؛ زانیاری پشتڕاستنەکراو و ڕاستەوخۆ لە یەک جیا بکەرەوە.',
      'وضح المصادر والمؤشرات التي يجب فحصها لتقييم الحالة الحالية للمنفذ، مع التمييز بين المعلومات المباشرة وغير المؤكدة.',
      'Explain which sources and indicators to check for the current crossing status, clearly separating live verified information from unverified reports.',
    ),
  ],
  currency: [
    entry(
      'کاریگەری USD/IQD',
      'تأثير USD/IQD',
      'USD/IQD cost impact',
      'بە سێ سناریۆی نرخی USD/IQD کاریگەری لە نرخی کڕین، گواستنەوە، گومرگ و هامشەکەم بخەمڵێنە و فرضییەکان ڕوون بکەرەوە.',
      'قدّر أثر سعر USD/IQD بثلاثة سيناريوهات على الشراء والنقل والجمارك والهامش، مع توضيح الافتراضات.',
      'Estimate the impact of three USD/IQD scenarios on purchasing, freight, customs, and margin, with explicit assumptions.',
    ),
    entry(
      'پلانی پاراستن لە گۆڕانی دراو',
      'خطة التحوط من العملة',
      'Currency-risk plan',
      'پلانی کەمکردنەوەی مەترسی گۆڕانی دراو بۆ مامەڵەی هاوردە بنووسە؛ کاتی پارەدان، بەشکردنی پارەدان و buffer لەخۆبگرێت.',
      'اكتب خطة لتقليل مخاطر العملة في صفقة استيراد، تشمل توقيت الدفع وتقسيم الدفعات وهامش الأمان.',
      'Create a currency-risk plan for an import transaction covering payment timing, staged payments, and contingency buffers.',
    ),
    entry(
      'نرخی break-even',
      'سعر التعادل',
      'Break-even exchange rate',
      'فۆرمولا و خشتەیەک بۆ دۆزینەوەی نرخی دراوی break-even ـی کاڵاکەم دروست بکە و زانیاری پێویست لێم بپرسە.',
      'أنشئ معادلة وجدولاً لحساب سعر الصرف عند نقطة التعادل لمنتجي، واطلب مني المدخلات اللازمة.',
      'Build a formula and table for my product’s break-even exchange rate and ask for the required inputs.',
    ),
    entry(
      'بەراوردی پێشنیاری پارەدان',
      'مقارنة عروض الدفع',
      'Compare payment offers',
      'دوو پێشنیاری دابینکەر بە دراو و مەرجی پارەدانی جیاواز بەراورد بکە و total landed cost ـی هەریەک بخەمڵێنە.',
      'قارن عرضين لموردين بعملات وشروط دفع مختلفة، وقدّر التكلفة النهائية الواصلة لكل منهما.',
      'Compare two supplier offers with different currencies and payment terms, estimating the total landed cost of each.',
    ),
    entry(
      'سیاسەتی نرخدانان',
      'سياسة التسعير',
      'Pricing policy',
      'سیاسەتی نرخدانانێک بۆ کاڵای هاوردەکراو پێشنیار بکە کە گۆڕانی دراو، تێچووی جێگرەوە، هامش و ماوەی نوێکردنەوە لەخۆبگرێت.',
      'اقترح سياسة تسعير لمنتج مستورد تراعي تقلب العملة وتكلفة الاستبدال والهامش ودورية تحديث الأسعار.',
      'Propose a pricing policy for imported goods that accounts for currency volatility, replacement cost, margin, and repricing frequency.',
    ),
  ],
  cost: [
    entry(
      'خەمڵاندنی landed cost',
      'تقدير التكلفة الواصلة',
      'Estimate landed cost',
      'زانیاری پێویستم لێ بپرسە و total landed cost ـی بارەکەم بە کڕین، گواستنەوە، بیمە، گومرگ، خەرجی بەندر و گەیاندنی ناوخۆ بخەمڵێنە.',
      'اطلب المدخلات اللازمة وقدّر التكلفة الواصلة الكلية لشحنتي، بما يشمل الشراء والنقل والتأمين والجمارك ورسوم المنفذ والتوصيل الداخلي.',
      'Ask for the required inputs and estimate my shipment’s total landed cost, including purchase, freight, insurance, customs, port, and inland delivery.',
    ),
    entry(
      'بەراوردی FCL و LCL',
      'مقارنة FCL وLCL',
      'Compare FCL and LCL',
      'بۆ قەبارە و کێشی بارەکەم FCL و LCL لە ڕووی نرخ، ماوە، مەترسی و خاڵی break-even بەراورد بکە.',
      'قارن FCL وLCL لشحنتي من حيث السعر والمدة والمخاطر ونقطة التعادل حسب الحجم والوزن.',
      'Compare FCL and LCL for my cargo by cost, time, risk, and break-even volume or weight.',
    ),
    entry(
      'کێشی قەبارەیی',
      'الوزن الحجمي',
      'Volumetric weight',
      'کێشی قەبارەیی و chargeable weight ـی بارەکەم هەژمار بکە، فاکتەری هەڵبژێردراو ڕوون بکەرەوە و ئەنجامەکە بە کێشی ڕاستەقینە بەراورد بکە.',
      'احسب الوزن الحجمي والوزن القابل للفوترة لشحنتي، واشرح معامل الحساب وقارنه بالوزن الفعلي.',
      'Calculate volumetric and chargeable weight for my shipment, explain the divisor, and compare it with actual weight.',
    ),
    entry(
      'کەمکردنەوەی تێچوو',
      'خفض التكلفة اللوجستية',
      'Reduce logistics cost',
      'بەپێی breakdown ـی تێچوو، ٥ دەرفەتی کەمکردنەوەی خەرجی دیاری بکە بەبێ کەمکردنەوەی compliance یان پاراستنی بار.',
      'استناداً إلى تفصيل التكلفة، حدد خمس فرص لخفض المصروفات دون الإضرار بالامتثال أو سلامة الشحنة.',
      'Using the cost breakdown, identify five savings opportunities without weakening compliance or cargo protection.',
    ),
    entry(
      'بودجەی مەترسی',
      'ميزانية الطوارئ',
      'Contingency budget',
      'بودجەی contingency بۆ دواکەوتن، demurrage، گۆڕانی دراو و پشکنینی زیادە دروست بکە و ڕێژەی هەر buffer ـێک ڕوون بکەرەوە.',
      'أنشئ ميزانية احتياطية للتأخير وأجور الأرضيات وتقلب العملة والفحص الإضافي، مع شرح نسبة كل هامش.',
      'Create a contingency budget for delays, demurrage, currency movement, and additional inspection, explaining each buffer.',
    ),
  ],
  kyc: [
    entry(
      'checklist ـی KYC',
      'قائمة KYC',
      'KYC checklist',
      'بەپێی جۆری کۆمپانیا checklist ـێکی KYC دروست بکە کە ناسنامە، تۆمار، خاوەن سوود، ناونیشان، باج و مۆڵەت لەخۆبگرێت.',
      'أنشئ قائمة KYC حسب نوع الشركة تشمل الهوية والتسجيل والمستفيد الحقيقي والعنوان والضرائب والتراخيص.',
      'Create a KYC checklist for the company type covering identity, registration, beneficial ownership, address, tax, and licensing.',
    ),
    entry(
      'پشکنینی تەواوی مەلەف',
      'مراجعة اكتمال الملف',
      'Review file completeness',
      'مەلەفی KYC ـەکەم بەپێی لیستی بەڵگەنامەکان هەڵبسەنگێنە و بەڵگەی ون، بەسەرچوو یان ناهاوتا دیاری بکە.',
      'راجع ملف KYC الخاص بي وحدد المستندات الناقصة أو المنتهية أو غير المتطابقة.',
      'Review my KYC package and identify missing, expired, or inconsistent documents.',
    ),
    entry(
      'خاوەنداری سوودمەند',
      'المستفيد الحقيقي',
      'Beneficial ownership',
      'ڕێنماییم بکە چۆن خاوەن سوودمەندی کۆتایی دیاری و تۆمار بکەم، بەڵام خاڵە یاساییەکان بۆ پشتڕاستکردنەوە لەگەڵ پسپۆڕ دیاری بکە.',
      'اشرح كيفية تحديد وتوثيق المستفيد الحقيقي، مع تحديد النقاط القانونية التي يجب التحقق منها مع مختص.',
      'Explain how to identify and document ultimate beneficial ownership, flagging legal points for professional verification.',
    ),
    entry(
      'ئامادەکاری بۆ پشکنین',
      'الاستعداد للمراجعة',
      'Prepare for review',
      'پلانی ئامادەکاری بۆ پشکنینی KYC بنووسە کە ناونانی فایل، وەرگێڕان، پشتڕاستکردنەوە و وەڵامدانەوەی پرسیارەکان لەخۆبگرێت.',
      'اكتب خطة للاستعداد لمراجعة KYC تشمل تسمية الملفات والترجمة والتصديق والرد على الاستفسارات.',
      'Create a KYC review-preparation plan covering file naming, translation, certification, and query responses.',
    ),
    entry(
      'نوێکردنەوەی KYC',
      'تحديث KYC',
      'KYC renewal schedule',
      'خشتەیەکی ساڵانە بۆ نوێکردنەوە و بەسەرچوونی بەڵگەنامەکانی KYC دروست بکە و بەرپرسی هەر کارێک دیاری بکە.',
      'أنشئ جدولاً سنوياً لتحديث وانتهاء مستندات KYC مع تحديد مسؤول كل إجراء.',
      'Create an annual KYC document renewal and expiry schedule with an owner for each action.',
    ),
  ],
  procurement: [
    entry(
      'ئامادەکردنی RFQ',
      'إعداد RFQ',
      'Prepare an RFQ',
      'RFQ ـێکی پیشەیی بۆ کاڵاکەم ئامادە بکە کە specification، بڕ، کوالێتی، Incoterm، کاتی گەیاندن، پارەدان و بەڵگەنامەکان لەخۆبگرێت.',
      'أعد RFQ مهنياً لمنتجي يشمل المواصفات والكمية والجودة وIncoterm وموعد التسليم والدفع والمستندات.',
      'Prepare a professional RFQ covering specifications, quantity, quality, Incoterm, delivery, payment, and required documents.',
    ),
    entry(
      'هەڵسەنگاندنی دابینکەر',
      'تقييم المورد',
      'Evaluate a supplier',
      'scorecard ـێک بۆ هەڵسەنگاندنی دابینکەر لەسەر ناسنامە، توانای بەرهەمهێنان، کوالێتی، نرخ، delivery، compliance و reference دروست بکە.',
      'أنشئ بطاقة تقييم للمورد تشمل الهوية والطاقة الإنتاجية والجودة والسعر والتسليم والامتثال والمراجع.',
      'Create a supplier scorecard covering identity, production capacity, quality, price, delivery, compliance, and references.',
    ),
    entry(
      'بەراوردی quotation ـەکان',
      'مقارنة عروض الأسعار',
      'Compare quotations',
      'سێ quotation بە total landed cost، مەرجی پارەدان، lead time، warranty و مەترسی بەراورد بکە و ranking ـێکی ڕوون بدە.',
      'قارن ثلاثة عروض حسب التكلفة الواصلة وشروط الدفع ومدة التوريد والضمان والمخاطر، وقدم ترتيباً واضحاً.',
      'Compare three quotations by landed cost, payment terms, lead time, warranty, and risk, and provide a clear ranking.',
    ),
    entry(
      'پشکنینی پێش پارەدان',
      'فحص ما قبل الدفع',
      'Pre-payment due diligence',
      'checklist ـێکی due diligence پێش deposit یان پارەدانی تەواو دروست بکە بۆ کەمکردنەوەی ساختەکاری و شکاندنی مەرج.',
      'أنشئ قائمة عناية واجبة قبل دفع العربون أو كامل المبلغ لتقليل الاحتيال ومخاطر الإخلال.',
      'Create a due-diligence checklist before deposit or full payment to reduce fraud and non-performance risk.',
    ),
    entry(
      'پلانی negotiation',
      'خطة التفاوض',
      'Negotiation plan',
      'پلانی دانوستاندن لەگەڵ دابینکەر بنووسە کە target price، MOQ، sample، پارەدان، delivery، penalty و BATNA لەخۆبگرێت.',
      'اكتب خطة تفاوض مع المورد تشمل السعر المستهدف وMOQ والعينة والدفع والتسليم والجزاءات وBATNA.',
      'Write a supplier negotiation plan covering target price, MOQ, samples, payment, delivery, penalties, and BATNA.',
    ),
  ],
  tracking: [
    entry(
      'لێکدانەوەی دۆخی بار',
      'تفسير حالة الشحنة',
      'Interpret shipment status',
      'دۆخی tracking ـی بارەکەم بە زمانی سادە لێکبدەرەوە و بڵێ قۆناغی داهاتوو، کاتی پێشبینیکراو و کاری پێویست چییە.',
      'فسر حالة تتبع شحنتي بلغة واضحة، وحدد المرحلة التالية والوقت المتوقع والإجراء المطلوب.',
      'Explain my shipment tracking status in plain language and identify the next milestone, expected timing, and required action.',
    ),
    entry(
      'پلانی بارێکی دواکەوتوو',
      'خطة شحنة متأخرة',
      'Delayed-shipment plan',
      'بەپێی شوێنی ئێستا و ماوەی دواکەوتن، پلانی escalation بۆ carrier، forwarder، broker و کڕیار دروست بکە.',
      'أنشئ خطة تصعيد مع الناقل والوكيل والمخلص والعميل حسب موقع الشحنة ومدة التأخير.',
      'Create an escalation plan for the carrier, forwarder, broker, and customer based on the shipment location and delay duration.',
    ),
    entry(
      'پشکنینی tracking number',
      'فحص رقم التتبع',
      'Validate tracking details',
      'پێم بڵێ بۆ پشتڕاستکردنەوەی tracking number یان bill of lading کام زانیاری و سەرچاوەی فەرمی پێویستە.',
      'وضح البيانات والمصادر الرسمية اللازمة للتحقق من رقم التتبع أو بوليصة الشحن.',
      'Explain which data and official sources are needed to validate a tracking number or bill of lading.',
    ),
    entry(
      'ئاگادارکردنەوەی کڕیار',
      'إشعار العميل',
      'Customer status update',
      'نامەیەکی پیشەیی بۆ ئاگادارکردنەوەی کڕیار لە دۆخی بار، هۆکاری دواکەوتن، ETA و هەنگاوی داهاتوو بنووسە.',
      'اكتب تحديثاً مهنياً للعميل يوضح حالة الشحنة وسبب التأخير وETA والخطوة التالية.',
      'Draft a professional customer update covering shipment status, delay cause, ETA, and next action.',
    ),
    entry(
      'خشتەی milestone ـەکان',
      'جدول مراحل الشحنة',
      'Shipment milestone table',
      'خشتەی milestone ـەکانی بار لە pickup تا delivery دروست بکە و بەڵگەنامە، بەرپرسی کار و alert ـی هەر قۆناغێک زیاد بکە.',
      'أنشئ جدول مراحل للشحنة من الاستلام إلى التسليم، مع المستند والمسؤول والتنبيه لكل مرحلة.',
      'Create a shipment milestone table from pickup to delivery, including the document, owner, and alert for each stage.',
    ),
  ],
  map: [
    entry(
      'هەڵبژاردنی ڕێگای لۆجستیکی',
      'اختيار المسار اللوجستي',
      'Choose a logistics route',
      'بەپێی سەرچاوە، مەبەست، جۆری بار و priority، سێ ڕێگای لۆجستیکی بە کات، تێچوو، گومرگ و مەترسی بەراورد بکە.',
      'قارن ثلاثة مسارات لوجستية حسب المنشأ والوجهة ونوع الشحنة والأولوية، من حيث الوقت والتكلفة والجمارك والمخاطر.',
      'Compare three logistics routes based on origin, destination, cargo, and priority by time, cost, customs, and risk.',
    ),
    entry(
      'باشترین دەروازەی چوونەژوورەوە',
      'أفضل منفذ دخول',
      'Best Iraqi entry point',
      'پێوەرەکان بۆ هەڵبژاردنی باشترین بەندر یان مەرزی عێراق بۆ بارەکەم دیاری بکە و زانیاری پێویستم لێ بپرسە.',
      'حدد معايير اختيار أفضل ميناء أو منفذ عراقي لشحنتي، واطلب مني البيانات اللازمة.',
      'Define the criteria for choosing the best Iraqi port or land entry point for my shipment and ask for the required inputs.',
    ),
    entry(
      'پلانی ڕێگای جێگرەوە',
      'خطة مسار بديل',
      'Alternate-route plan',
      'ڕێگای سەرەکی و دوو ڕێگای جێگرەوە بۆ کاتی داخستن، قەرەباڵغی یان دواکەوتن دیاری بکە و trigger ـی گۆڕینی ڕێگا بنووسە.',
      'حدد مساراً رئيسياً ومسارين بديلين عند الإغلاق أو الازدحام أو التأخير، واكتب محفزات تغيير المسار.',
      'Define a primary and two alternate routes for closure, congestion, or delay, with route-switch triggers.',
    ),
    entry(
      'خشتەی کات و دووری',
      'جدول الزمن والمسافة',
      'Time and distance matrix',
      'خشتەیەکی بەراوردی دووری، transit time، checkpoint و کاتی contingency بۆ ڕێگاکانی دیاریکراو دروست بکە.',
      'أنشئ مصفوفة مقارنة للمسافة ووقت العبور ونقاط التوقف ووقت الطوارئ للمسارات المحددة.',
      'Create a comparison matrix of distance, transit time, checkpoints, and contingency time for specified routes.',
    ),
    entry(
      'نەخشەی خاڵە گرنگەکان',
      'خريطة النقاط الحرجة',
      'Critical-point map',
      'خاڵە گرنگەکانی ڕێگای بارەکەم وەک بەندر، مەرز، کۆگا، checkpoint و شوێنی مەترسی لیست بکە و بڵێ چی لە هەر خاڵێکدا پشکنین بکرێت.',
      'اسرد النقاط الحرجة لمسار شحنتي مثل الميناء والمنفذ والمخزن ونقاط التفتيش ومواقع المخاطر، وما يجب فحصه في كل نقطة.',
      'List critical points on my shipment route, such as ports, borders, warehouses, checkpoints, and risk locations, with checks for each.',
    ),
  ],
  inquiry: [
    entry(
      'داوای دیمۆی پلاتفۆرم',
      'طلب عرض للمنصة',
      'Request a platform demo',
      'داواکارییەکی پیشەیی بۆ دیمۆی AI Gate Iraq بنووسە و ئامانج، جۆری کۆمپانیا، بەشە گرنگەکان و کاتی گونجاو تێدا دابنێ.',
      'اكتب طلباً مهنياً لعرض AI Gate Iraq يتضمن الهدف ونوع الشركة والأقسام المهمة والوقت المناسب.',
      'Draft a professional AI Gate Iraq demo request including objective, company type, priority modules, and preferred timing.',
    ),
    entry(
      'پرسیاری نرخ و پلاندانان',
      'استفسار عن الأسعار والخطط',
      'Pricing and plan inquiry',
      'نامەیەکی پەیوەندی بنووسە بۆ پرسیارکردن لە plan، نرخ، سنووری بەکارهێنان، onboarding و support.',
      'اكتب رسالة للاستفسار عن الخطط والأسعار وحدود الاستخدام وonboarding والدعم.',
      'Draft an inquiry about plans, pricing, usage limits, onboarding, and support.',
    ),
    entry(
      'onboarding ـی کۆمپانیا',
      'تهيئة الشركة',
      'Company onboarding',
      'checklist ـێک بۆ ئامادەکردنی کۆمپانیاکەم بۆ بەکارهێنانی پلاتفۆرم دروست بکە؛ بەکارهێنەر، role، data و workflow لەخۆبگرێت.',
      'أنشئ قائمة لتجهيز شركتي لاستخدام المنصة تشمل المستخدمين والأدوار والبيانات ومسارات العمل.',
      'Create a company onboarding checklist covering users, roles, data, and workflows.',
    ),
    entry(
      'داوای integration',
      'طلب تكامل',
      'Integration request',
      'داواکارییەکی تەکنیکی بۆ پەیوەستکردنی AI Gate Iraq بە ERP، CRM یان سیستەمی ناوخۆیی بنووسە و data flow و security requirements تێدا دابنێ.',
      'اكتب طلب تكامل تقني بين AI Gate Iraq وERP أو CRM أو نظام داخلي، مع تدفق البيانات ومتطلبات الأمان.',
      'Draft a technical integration request for ERP, CRM, or an internal system, including data flow and security requirements.',
    ),
    entry(
      'داوای پشتیوانی',
      'طلب دعم',
      'Support request',
      'ticket ـێکی ڕوون بۆ کێشەیەکی تەکنیکی بنووسە کە هەنگاوەکانی دووبارەکردنەوە، ئەنجامی چاوەڕوانکراو و کاریگەری لەخۆبگرێت.',
      'اكتب تذكرة دعم واضحة لمشكلة تقنية تشمل خطوات التكرار والنتيجة المتوقعة والأثر.',
      'Draft a clear technical support ticket with reproduction steps, expected result, and impact.',
    ),
  ],
  audit: [
    entry(
      'وردبینی ئامادەیی production',
      'تدقيق جاهزية الإنتاج',
      'Production-readiness audit',
      'checklist ـێکی وردبینی production بۆ security، performance، availability، observability، backup و recovery دروست بکە.',
      'أنشئ قائمة تدقيق لجاهزية الإنتاج تشمل الأمان والأداء والتوافر والمراقبة والنسخ الاحتياطي والاستعادة.',
      'Create a production-readiness audit checklist covering security, performance, availability, observability, backup, and recovery.',
    ),
    entry(
      'وردبینی UI/UX',
      'تدقيق UI/UX',
      'UI/UX audit',
      'UI/UX ـی پلاتفۆرم بەپێی accessibility، responsive layout، RTL، navigation، feedback و task completion هەڵبسەنگێنە.',
      'قيّم UI/UX للمنصة حسب إمكانية الوصول والاستجابة وRTL والتنقل والتغذية الراجعة وإكمال المهام.',
      'Assess the platform UI/UX by accessibility, responsiveness, RTL, navigation, feedback, and task completion.',
    ),
    entry(
      'پلان بۆ performance',
      'خطة تحسين الأداء',
      'Performance plan',
      'پلانی پێشینەبەندی بۆ کەمکردنەوەی bundle، lazy loading، route splitting، caching و Core Web Vitals بنووسە.',
      'اكتب خطة مرتبة لتقليل الحزم وlazy loading وتقسيم المسارات والتخزين المؤقت وCore Web Vitals.',
      'Write a prioritized plan for bundle reduction, lazy loading, route splitting, caching, and Core Web Vitals.',
    ),
    entry(
      'وردبینی security',
      'تدقيق الأمان',
      'Security audit',
      'threat model و checklist ـێکی security بۆ auth، Firestore، Storage، App Check، CSP، rate limiting و secrets دروست بکە.',
      'أنشئ نموذج تهديد وقائمة أمان للمصادقة وFirestore وStorage وApp Check وCSP وتحديد المعدل والأسرار.',
      'Create a threat model and security checklist for auth, Firestore, Storage, App Check, CSP, rate limiting, and secrets.',
    ),
    entry(
      'پێشینەبەندی کێشەکان',
      'ترتيب مشكلات المنصة',
      'Prioritize platform issues',
      'کێشەکان بە severity، کاریگەری بەکارهێنەر، مەترسی کاروبار، هەوڵی چاککردن و dependency پۆلێن بکە و roadmap بدە.',
      'رتب المشكلات حسب الشدة وتأثير المستخدم ومخاطر الأعمال وجهد الإصلاح والاعتماديات، وقدم خارطة طريق.',
      'Prioritize issues by severity, user impact, business risk, fix effort, and dependencies, then provide a roadmap.',
    ),
  ],
};

export const getServicePromptChips = (
  service: ServiceKey,
  lang: PromptLanguage,
): PromptChip[] => {
  const prompts = SERVICE_PROMPTS[service] || SERVICE_PROMPTS.assistant;
  return prompts.map((item) => ({
    label: item.label[lang],
    prompt: item.prompt[lang],
  }));
};
